### PR TITLE
Errors in OAuth2 how to examples

### PR DESCRIPTION
**Pull request by x-user**
Fix minor errors in OAuth2 how to, but huma.WriteErr requires huma.API as first argument and there no way to obtain it in middleware. I was thinking about replacing it with http.Error, but it requires http.ResponseWriter and huma.Context doesn't implement it. So i'm stuck there.

### CODE REVIEW

**Comment by x-user** [comment]
I can use
```go
ctx.SetStatus(http.StatusUnauthorized)
ctx.BodyWriter().Write([]byte(http.StatusText(http.StatusUnauthorized)))
```
But it looks kinda ugly.

**Comment by danielgtaylor** [comment]
@x-user thanks for fixing this up! You could maybe pass the `api` in when creating the middleware, then you get content negotiation and the normal error model in the error response:

```go
api.UseMiddleware(NewAuthMiddleware(api, "https://example.com/.well-known/jwks.json"))
```

**Comment by x-user** [comment]
Yes closures can solve this. Then i will make it this way.

**Review by danielgtaylor — APPROVED** [review]
Great, thank you! 🚀

**Pull request merged**
